name: Build and Release WebP Converter

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed webp_converter.py \
            --icon icon.ico || true
        shell: bash

      - name: Rename output for OS
        run: |
          mkdir -p dist_out
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            mv dist/webp_converter.exe dist_out/webp_converter-windows.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            mv dist/webp_converter dist_out/webp_converter-mac
          else
            mv dist/webp_converter dist_out/webp_converter-linux
          fi
        shell: bash

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: webp_converter-${{ runner.os }}
          path: dist_out/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist_all

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist_all/**/*
